//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.13 at 11:53:32 AM EEST 
//

package ee.ut.model.sim;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Resource complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Resource">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ResourceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ResourceAmount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Resource", propOrder = { "resourceType", "resourceAmount" })
public class Resource {

	@XmlElement(name = "ResourceType", required = true)
	protected String resourceType;
	@XmlElement(name = "ResourceAmount")
	protected int resourceAmount;

	/**
	 * Gets the value of the resourceType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getResourceType() {
		return resourceType;
	}

	/**
	 * Sets the value of the resourceType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setResourceType(String value) {
		this.resourceType = value;
	}

	/**
	 * Gets the value of the resourceAmount property.
	 * 
	 */
	public int getResourceAmount() {
		return resourceAmount;
	}

	/**
	 * Sets the value of the resourceAmount property.
	 * 
	 */
	public void setResourceAmount(int value) {
		this.resourceAmount = value;
	}

}
