//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.15 at 06:18:08 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.wfmc.org/2008/XPDL2.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.wfmc._2008.xpdl2;
