//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.25 at 07:25:36 PM EET 
//


package ee.ut.model.sim;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SimulationProfile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SimulationProfile">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StartTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EndTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TokensInBundle" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="TotalTokens" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="CostPerToken" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Resources" type="{}Resources"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SimulationProfile", propOrder = {
    "startTime",
    "endTime",
    "tokensInBundle",
    "totalTokens",
    "costPerToken",
    "resources"
})
public class SimulationProfile {

    @XmlElement(name = "StartTime", required = true)
    protected String startTime;
    @XmlElement(name = "EndTime", required = true)
    protected String endTime;
    @XmlElement(name = "TokensInBundle")
    protected int tokensInBundle;
    @XmlElement(name = "TotalTokens")
    protected int totalTokens;
    @XmlElement(name = "CostPerToken")
    protected int costPerToken;
    @XmlElement(name = "Resources", required = true)
    protected Resources resources;

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartTime(String value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the endTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * Sets the value of the endTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndTime(String value) {
        this.endTime = value;
    }

    /**
     * Gets the value of the tokensInBundle property.
     * 
     */
    public int getTokensInBundle() {
        return tokensInBundle;
    }

    /**
     * Sets the value of the tokensInBundle property.
     * 
     */
    public void setTokensInBundle(int value) {
        this.tokensInBundle = value;
    }

    /**
     * Gets the value of the totalTokens property.
     * 
     */
    public int getTotalTokens() {
        return totalTokens;
    }

    /**
     * Sets the value of the totalTokens property.
     * 
     */
    public void setTotalTokens(int value) {
        this.totalTokens = value;
    }

    /**
     * Gets the value of the costPerToken property.
     * 
     */
    public int getCostPerToken() {
        return costPerToken;
    }

    /**
     * Sets the value of the costPerToken property.
     * 
     */
    public void setCostPerToken(int value) {
        this.costPerToken = value;
    }

    /**
     * Gets the value of the resources property.
     * 
     * @return
     *     possible object is
     *     {@link Resources }
     *     
     */
    public Resources getResources() {
        return resources;
    }

    /**
     * Sets the value of the resources property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resources }
     *     
     */
    public void setResources(Resources value) {
        this.resources = value;
    }

}
