//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.22 at 03:03:07 PM EEST 
//

package ee.ut.model.sim;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Task complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Task">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ResourceWaitTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProcessingTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ResourceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Task", propOrder = { "id", "resourceWaitTime",
		"processingTime", "resourceType" })
public class Task {

	@XmlElement(name = "Id", required = true)
	protected String id;
	@XmlElement(name = "ResourceWaitTime", required = true)
	protected String resourceWaitTime;
	@XmlElement(name = "ProcessingTime", required = true)
	protected String processingTime;
	@XmlElement(name = "ResourceType", required = true)
	protected String resourceType;

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setId(String value) {
		this.id = value;
	}

	/**
	 * Gets the value of the resourceWaitTime property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getResourceWaitTime() {
		return resourceWaitTime;
	}

	/**
	 * Sets the value of the resourceWaitTime property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setResourceWaitTime(String value) {
		this.resourceWaitTime = value;
	}

	/**
	 * Gets the value of the processingTime property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProcessingTime() {
		return processingTime;
	}

	/**
	 * Sets the value of the processingTime property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setProcessingTime(String value) {
		this.processingTime = value;
	}

	/**
	 * Gets the value of the resourceType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getResourceType() {
		return resourceType;
	}

	/**
	 * Sets the value of the resourceType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setResourceType(String value) {
		this.resourceType = value;
	}

}
